default_install_hook_types: [pre-commit, pre-push, commit-msg]

repos:
  - repo: local
    hooks:
      - id: ts-check
        name: Check TS
        entry: npm run ts:check
        language: system
        files: \.ts$
        stages:
          - pre-commit
      - id: compile
        name: Compile
        entry: npm run compile
        language: system
        files: \.ts$
        pass_filenames: false
        stages:
          - pre-commit
      - id: package
        name: Package
        entry: npm run package
        language: system
        stages:
          - pre-push
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.7.2
    hooks:
      - id: shellcheck
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        stages:
          - pre-commit
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3 # pick a git hash / tag to point to
    hooks:
      - id: editorconfig-checker
        alias: ec
        exclude: LICENSE
